[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173

# Правило для SPA-приложений
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Настройки окружения
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Кэширование для улучшения производительности
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    
# Обработка функций Netlify
[functions]
  directory = "netlify/functions"
